In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.Container {width:85% !important;}
div.CodeMirror {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.output_area pre {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.output_wrapper pre {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.input {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
</style>
"""))

In [2]:
import pandas as pd # 데이터 프레임화 해야하기 때문
import numpy as np

# 포지션별 데이터를 하나로

In [120]:
# ▶ 1. 데이터 셋 불러오기
df1 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Spain/spa_2021_defensive_stats.csv',
                  encoding = "UTF8").drop(['Unnamed: 0'],axis=1)
df2 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Spain/spa_2021_offensive_stats.csv',
                  encoding = "UTF8").drop(['Unnamed: 0'],axis=1)
df3 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Spain/spa_2021_passing_stats.csv', 
                  encoding = "UTF8").drop(['Unnamed: 0'],axis=1)

In [121]:
# ▶ 2. 결측치 변경 및 필요없는 열 제거
df1 = df1.replace(np.nan, "0")
df2 = df2.replace(np.nan, "0")
df3 = df3.replace(np.nan, "0")

df1.head()

          Player Tackles Inter Fouls Offsides Clear  Drb Blocks OwnG  Rating
0   Lionel Messi     0.5   0.2   0.6        0     0  0.3      0    0    8.52
1  Ángel Jiménez       0     0     0        0   2.0    0      0    0    8.24
2  Gerard Moreno     0.7   0.5   1.3        0   0.8  0.8    0.1    0    7.62
3  Karim Benzema     0.2   0.2   0.5        0   0.7  0.3    0.1    0    7.57
4      Ansu Fati     1.3   0.4   0.9        0     0  1.1      0    0    7.38

In [122]:
df1.drop(['Rating', 'Drb', 'Offsides'], axis = 1, inplace = True)
df2.drop(['Rating', 'Player'], axis = 1, inplace = True)
df3.drop(['Rating', 'Player'], axis = 1, inplace = True)

df1.head()

          Player Tackles Inter Fouls Clear Blocks OwnG
0   Lionel Messi     0.5   0.2   0.6     0      0    0
1  Ángel Jiménez       0     0     0   2.0      0    0
2  Gerard Moreno     0.7   0.5   1.3   0.8    0.1    0
3  Karim Benzema     0.2   0.2   0.5   0.7    0.1    0
4      Ansu Fati     1.3   0.4   0.9     0      0    0

In [123]:
# 데이터 결합
new_df = pd.concat([df1, df2, df3], axis = 1)

new_df.head(20)

,Player,Tackles,Inter,Fouls,Clear,Blocks,OwnG,Goals,Assists,SpG,...,Off,Disp,UnsTch,Assists,KeyP,AvgP,PS%,Crosses,LongB,ThrB
0,Lionel Messi,0.5,0.2,0.6,0,0,0,30.0,9.0,5.6,...,0.2,2.5,1.6,9.0,2.2,64.2,85.1,1.0,2.0,0.2
1,Ángel Jiménez,0,0,0,2.0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,31.0,45.2,0.0,9.0,0.0
2,Gerard Moreno,0.7,0.5,1.3,0.8,0.1,0,23.0,7.0,2.9,...,0.6,1.8,2.8,7.0,1.3,32.0,69.7,0.4,1.8,0.2
3,Karim Benzema,0.2,0.2,0.5,0.7,0.1,0,23.0,9.0,3.6,...,0.7,1.1,1.7,9.0,1.1,35.6,84.6,0.1,1.3,0.1
4,Ansu Fati,1.3,0.4,0.9,0,0,0,4.0,0.0,2.0,...,0.3,1.1,1.6,0.0,1.3,28.1,83.8,0.3,0.0,0.1
5,Casemiro,2.5,2.1,1.6,1.6,0.5,0,6.0,4.0,1.4,...,0.1,0.8,0.9,4.0,0.7,56.8,83.9,0.1,4.4,0.0
6,Iago Aspas,0.3,0.5,0.7,0.6,0.1,0,14.0,13.0,1.5,...,0.4,0.8,1.7,13.0,1.9,37.1,78.8,0.2,1.5,0.2
7,Marcos Llorente,1.9,0.8,1.6,0.6,0.1,0,12.0,11.0,1.3,...,0.2,1.4,1.1,11.0,1.2,33.6,84.6,0.4,1.3,0.1
8,Mikel Merino,2.3,1.2,3.0,1.0,0.3,0,2.0,4.0,1.3,...,0.1,1.0,1.6,4.0,1.1,45.3,76.7,0.1,2.1,0.2
9,Toni Kroos,1.5,0.5,1.0,0.3,0.2,0,3.0,10.0,1.2,...,0.0,0.3,0.5,10.0,2.4,72.2,93.6,1.3,8.2,0.1
10,Joselu,0.7,0.4,1.2,1.5,0.1,0,11.0,3.0,2.5,...,0.4,1.0,2.4,3.0,0.8,27.4,58.6,0.1,0.9,0.0
11,Kieran Trippier,2.2,1.4,1.1,1.7,0.1,0,0.0,6.0,0.1,...,0.2,0.3,0.8,6.0,1.2,53.2,79.4,1.2,2.4,0.1
12,Lucas Vázquez,2.5,0.8,1.3,1.0,0,0,2.0,5.0,0.9,...,0.1,0.9,1.9,5.0,1.8,51.0,87.7,1.0,2.7,0.0
13,Geoffrey Kondogbia,3.2,1.6,1.6,1.6,0.2,0,0.0,0.0,0.8,...,0.0,0.2,0.4,0.0,0.0,37.4,85.6,0.0,4.6,0.0
14,Diego Llorente,1.0,2.0,2.0,4.0,1.0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,58.0,82.8,0.0,3.0,0.0
15,Antoine Griezmann,1.0,0.3,0.4,0.3,0,0,13.0,7.0,2.0,...,0.4,0.6,0.9,7.0,1.2,36.6,87.3,0.3,1.1,0.0
16,Javi Galán,2.4,1.1,1.6,1.4,0.1,0,1.0,2.0,0.2,...,0.1,1.1,1.8,2.0,1.1,35.4,80.2,1.3,1.8,0.0
17,Yannick Carrasco,0.9,0.6,1.0,0.3,0,0,6.0,10.0,1.4,...,0.1,1.7,2.0,10.0,1.6,28.2,80.7,0.6,0.7,0.1
18,Luis Suárez,0.3,0.2,0.7,0.4,0,0,21.0,3.0,3.3,...,1.0,0.8,1.9,3.0,0.8,18.0,71.8,0.1,0.6,0.1
19,Luka Modric,1.1,1.4,0.9,0.3,0.1,0,5.0,3.0,1.3,...,0.0,0.9,1.2,3.0,1.4,63.1,88.1,0.4,4.7,0.1

In [124]:
new_df.isna().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 23 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   583 non-null    bool
 1   Tackles  583 non-null    bool
 2   Inter    583 non-null    bool
 3   Fouls    583 non-null    bool
 4   Clear    583 non-null    bool
 5   Blocks   583 non-null    bool
 6   OwnG     583 non-null    bool
 7   Goals    583 non-null    bool
 8   Assists  583 non-null    bool
 9   SpG      583 non-null    bool
 10  KeyP     583 non-null    bool
 11  Drb      583 non-null    bool
 12  Fouled   583 non-null    bool
 13  Off      583 non-null    bool
 14  Disp     583 non-null    bool
 15  UnsTch   583 non-null    bool
 16  Assists  583 non-null    bool
 17  KeyP     583 non-null    bool
 18  AvgP     583 non-null    bool
 19  PS%      583 non-null    bool
 20  Crosses  583 non-null    bool
 21  LongB    583 non-null    bool
 22  ThrB     583 non-null    bool
dtypes: bool(23)
memory usage: 13.2 KB

In [125]:
#  ▶ 3. 데이터 저장
new_df.to_csv('D:/Gray_Bigdata\src/00_Projects/data/spa_2021_tot_stats.csv')

# 통합 데이터 만들기(리그별)

In [60]:
# ▶ 1. 데이터 불러오기
df1 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Italy/ita_2021_tot_stats.csv', 
                  encoding = 'UTF8').drop(['Unnamed: 0'],axis=1)
df2 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Italy/italy-serie-a-players-2020-to-2021-stats.csv', 
                  encoding = 'UTF8')

In [61]:
df1.sort_values(by='Player', inplace = True)
df2.sort_values(by='full_name', inplace = True)

In [62]:
df2.head()

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
1,Aaron Hickey,0,0,1970-01-01,Serie A,2020/2021,Midfielder,Bologna,763,364,...,1.77,51,69,153,0,0.59,329,294,-1,26
2,Aaron Ramsey,30,662169600,1990-12-26,Serie A,2020/2021,Midfielder,Juventus,1093,572,...,0.91,99,50,547,273,0.16,131,17,-1,9
3,Abdallah Basit,21,939945600,1999-10-15,Serie A,2020/2021,Midfielder,Benevento,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
4,Abdoul Hate Bane,20,985132800,2001-03-21,Serie A,2020/2021,Defender,Parma,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
5,Achraf Hakimi Mouh,22,910137600,1998-11-04,Serie A,2020/2021,Defender,Inter Milan,2671,1261,...,0.88,103,72,445,334,0.20,94,35,15,3

In [63]:
df2.drop(['birthday', 'birthday_GMT', 'league', 'season'], axis = 1, inplace = True)

df2.head()

,full_name,age,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
1,Aaron Hickey,0,Midfielder,Bologna,763,364,399,Scotland,11,5,...,1.77,51,69,153,0,0.59,329,294,-1,26
2,Aaron Ramsey,30,Midfielder,Juventus,1093,572,521,Wales,22,12,...,0.91,99,50,547,273,0.16,131,17,-1,9
3,Abdallah Basit,21,Midfielder,Benevento,0,0,0,Italy,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
4,Abdoul Hate Bane,20,Defender,Parma,0,0,0,Italy,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
5,Achraf Hakimi Mouh,22,Defender,Inter Milan,2671,1261,1410,Morocco,37,18,...,0.88,103,72,445,334,0.20,94,35,15,3

In [64]:
df2.rename(columns={'full_name' : 'Player'}, inplace = True)

df2.head()

,Player,age,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
1,Aaron Hickey,0,Midfielder,Bologna,763,364,399,Scotland,11,5,...,1.77,51,69,153,0,0.59,329,294,-1,26
2,Aaron Ramsey,30,Midfielder,Juventus,1093,572,521,Wales,22,12,...,0.91,99,50,547,273,0.16,131,17,-1,9
3,Abdallah Basit,21,Midfielder,Benevento,0,0,0,Italy,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
4,Abdoul Hate Bane,20,Defender,Parma,0,0,0,Italy,0,0,...,0.00,0,0,0,0,0.00,-1,-1,-1,-1
5,Achraf Hakimi Mouh,22,Defender,Inter Milan,2671,1261,1410,Morocco,37,18,...,0.88,103,72,445,334,0.20,94,35,15,3

In [65]:
df1.head()

,Player,Tackles,Inter,Fouls,Clear,Blocks,OwnG,Goals,Assists,SpG,...,Off,Disp,UnsTch,Assists.1,KeyP.1,AvgP,PS%,Crosses,LongB,ThrB
469,Aaron Hickey,1.1,1.4,1.0,1.1,0.1,0.0,0.0,0.0,0.2,...,0.0,0.7,1.5,0.0,0.2,29.1,88.4,0.2,1.4,0.0
122,Aaron Ramsey,1.0,0.3,0.9,0.3,0.1,0.0,2.0,4.0,1.1,...,0.1,0.4,1.4,4.0,1.4,31.8,87.1,0.5,1.5,0.0
50,Achraf Hakimi,1.4,0.6,0.8,0.4,0.0,0.0,7.0,8.0,1.1,...,0.2,0.5,1.5,8.0,1.0,32.7,84.5,0.8,0.9,0.0
179,Adam Marusic,1.1,1.1,0.5,1.3,0.2,1.0,2.0,3.0,0.8,...,0.1,0.6,0.7,3.0,0.8,37.3,85.4,0.4,1.6,0.0
207,Adam Ounas,0.4,0.4,0.4,0.0,0.0,0.0,0.0,0.0,0.9,...,0.1,1.4,1.6,0.0,1.0,15.9,72.1,0.4,1.0,0.0

In [66]:
new_df = pd.merge(df2, df1, how = 'left', left_on='Player', right_on='Player')
# df_INNER_JOIN = pd.merge(dataframe_A, dataframe_B, left_on='key', right_on='key', how='inner')
new_df.head()

,Player,age,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,...,Off,Disp,UnsTch,Assists.1,KeyP.1,AvgP,PS%,Crosses,LongB,ThrB
0,Aaron Hickey,0,Midfielder,Bologna,763,364,399,Scotland,11,5,...,0.0,0.7,1.5,0.0,0.2,29.1,88.4,0.2,1.4,0.0
1,Aaron Ramsey,30,Midfielder,Juventus,1093,572,521,Wales,22,12,...,0.1,0.4,1.4,4.0,1.4,31.8,87.1,0.5,1.5,0.0
2,Abdallah Basit,21,Midfielder,Benevento,0,0,0,Italy,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdoul Hate Bane,20,Defender,Parma,0,0,0,Italy,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Achraf Hakimi Mouh,22,Defender,Inter Milan,2671,1261,1410,Morocco,37,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
new_df.replace("", "0", inplace=True)
new_df.replace(np.nan, "0", inplace=True)

new_df.head(10)

,Player,age,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,appearances_home,...,Off,Disp,UnsTch,Assists.1,KeyP.1,AvgP,PS%,Crosses,LongB,ThrB
0,Aaron Hickey,0,Midfielder,Bologna,763,364,399,Scotland,11,5,...,0.0,0.7,1.5,0.0,0.2,29.1,88.4,0.2,1.4,0.0
1,Aaron Ramsey,30,Midfielder,Juventus,1093,572,521,Wales,22,12,...,0.1,0.4,1.4,4.0,1.4,31.8,87.1,0.5,1.5,0.0
2,Adam Ounas,24,Midfielder,Crotone,1516,780,736,Algeria,22,10,...,0.1,1.4,1.6,0.0,1.0,15.9,72.1,0.4,1.0,0.0
3,Adam Ounas,24,Midfielder,Crotone,1516,780,736,Algeria,22,10,...,0.6,1.5,2.5,3.0,1.4,30.2,83.0,0.5,2.3,0.2
4,Adrien Rabiot,26,Midfielder,Juventus,2312,1152,1160,France,34,16,...,0.0,0.4,1.1,2.0,0.3,41.6,90.8,0.1,1.2,0.0
5,Adrien Tameze,26,Midfielder,Hellas Verona,2312,1157,1155,France,33,16,...,0.1,0.8,1.2,0.0,0.4,30.5,80.0,0.2,1.8,0.0
6,Alberto Cerri,25,Forward,Cagliari,353,228,125,Italy,24,12,...,0.0,0.5,0.6,0.0,0.3,6.0,61.5,0.0,0.2,0.0
7,Alberto Paleari,28,Goalkeeper,Genoa,205,90,115,Italy,3,1,...,0.0,0.0,0.0,0.0,0.0,22.3,62.7,0.0,3.0,0.0
8,Albin Ekdal,31,Midfielder,Sampdoria,2301,1129,1172,Sweden,32,16,...,0.0,0.6,0.7,1.0,0.3,32.7,83.8,0.0,1.2,0.0
9,Aleksandar Kolarov,35,Defender,Inter Milan,387,279,108,Serbia,7,4,...,0.0,0.0,0.4,1.0,0.9,47.7,88.3,0.4,2.4,0.0

In [36]:
new_df.to_csv('D:/Gray_Bigdata/src/00_Projects/data/ger_2021_season.csv')

# 통합 데이터 만들기(5개 리그 전체)

In [133]:
df_1 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/England/england-premier-league-players-2020-to-2021-stats.csv', 
                   encoding='UTF8')
df_2 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/France/france-ligue-1-players-2020-to-2021-stats.csv', 
                  encoding='UTF8')
df_3 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Germany/germany-bundesliga-players-2020-to-2021-stats.csv', 
                  encoding='UTF8')
df_4 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Italy/italy-serie-a-players-2020-to-2021-stats.csv', 
                  encoding='UTF8')
df_5 = pd.read_csv('D:/Gray_Bigdata/src/00_Projects/data/20_21_players/Spain/spain-la-liga-players-2020-to-2021-stats.csv', 
                  encoding='UTF8')

In [134]:
tot_df = pd.concat([df_1, df_2, df_3, df_4, df_5])

tot_df.head()

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall,rank_in_league_top_attackers,rank_in_league_top_midfielders,rank_in_league_top_defenders,rank_in_club_top_scorer
0,Aaron Anthony Connolly,21,949017600,2000/01/28,Premier League,2020/2021,Forward,Brighton & Hove Albion,790,397,...,1.94,46,46,0,790,0.00,74,126,-1,6
1,Aaron Cresswell,31,629683200,1989/12/15,Premier League,2020/2021,Defender,West Ham United,3172,1552,...,1.13,79,88,1057,397,0.09,317,32,58,22
2,Aaron Ramsdale,23,895104000,1998/05/14,Premier League,2020/2021,Goalkeeper,Sheffield United,3420,1710,...,1.61,56,90,3420,0,0.03,394,403,131,16
3,Aaron Wan-Bissaka,23,880502400,1997/11/26,Premier League,2020/2021,Midfielder,Manchester United,3060,1530,...,0.97,93,90,1020,765,0.09,201,110,-1,10
4,Abdoulaye Doucouré,28,725846400,1993/01/01,Premier League,2020/2021,Midfielder,Everton,2452,1211,...,1.21,74,85,409,817,0.22,184,130,-1,7

In [136]:
tot_df.columns

Index(['full_name', 'age', 'birthday', 'birthday_GMT', 'league', 'season',
       'position', 'Current Club', 'minutes_played_overall',
       'minutes_played_home', 'minutes_played_away', 'nationality',
       'appearances_overall', 'appearances_home', 'appearances_away',
       'goals_overall', 'goals_home', 'goals_away', 'assists_overall',
       'assists_home', 'assists_away', 'penalty_goals', 'penalty_misses',
       'clean_sheets_overall', 'clean_sheets_home', 'clean_sheets_away',
       'conceded_overall', 'conceded_home', 'conceded_away',
       'yellow_cards_overall', 'red_cards_overall',
       'goals_involved_per_90_overall', 'assists_per_90_overall',
       'goals_per_90_overall', 'goals_per_90_home', 'goals_per_90_away',
       'min_per_goal_overall', 'conceded_per_90_overall',
       'min_per_conceded_overall', 'min_per_match', 'min_per_card_overall',
       'min_per_assist_overall', 'cards_per_90_overall',
       'rank_in_league_top_attackers', 'rank_in_league_top_midfielders',
       'rank_in_league_top_defenders', 'rank_in_club_top_scorer'],
      dtype='object')

In [137]:
tot_df.drop(columns=['birthday', 'birthday_GMT', 'season',
                     'rank_in_league_top_attackers', 'rank_in_league_top_midfielders',
                     'rank_in_league_top_defenders', 'rank_in_club_top_scorer'], inplace=True)

In [139]:
tot_df.rename(columns={'full_name' : 'players'}, inplace=True)

In [140]:
tot_df.sort_values(by='players', ascending=True, inplace=True)

tot_df[ : 15]

,players,age,league,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,...,goals_per_90_overall,goals_per_90_home,goals_per_90_away,min_per_goal_overall,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall
0,Aaron Anthony Connolly,21,Premier League,Forward,Brighton & Hove Albion,790,397,393,Republic of Ireland,17,...,0.23,0.23,0.23,395,1.94,46,46,0,790,0.00
1,Aaron Cresswell,31,Premier League,Defender,West Ham United,3172,1552,1620,England,36,...,0.00,0.00,0.00,0,1.13,79,88,1057,397,0.09
1,Aaron Hickey,0,Serie A,Midfielder,Bologna,763,364,399,Scotland,11,...,0.00,0.00,0.00,0,1.77,51,69,153,0,0.59
0,Aaron Kamardin,19,Ligue 1,Defender,Olympique Marseille,0,0,0,France,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
1,Aaron Leya Iseka,23,Ligue 1,Forward,Metz,1010,609,401,Belgium,21,...,0.36,0.15,0.67,253,1.34,67,48,253,0,0.36
2,Aaron Ramsdale,23,Premier League,Goalkeeper,Sheffield United,3420,1710,1710,England,38,...,0.00,0.00,0.00,0,1.61,56,90,3420,0,0.03
2,Aaron Ramsey,30,Serie A,Midfielder,Juventus,1093,572,521,Wales,22,...,0.16,0.16,0.17,547,0.91,99,50,547,273,0.16
3,Aaron Wan-Bissaka,23,Premier League,Midfielder,Manchester United,3060,1530,1530,England,34,...,0.06,0.06,0.06,1530,0.97,93,90,1020,765,0.09
0,Aarón Escandell Banacloche,25,La Liga,Goalkeeper,Granada CF,450,180,270,Spain,5,...,0.00,0.00,0.00,0,1.60,56,90,450,0,0.20
1,Aarón Martín,24,La Liga,Defender,Celta de Vigo,1539,668,871,Spain,19,...,0.00,0.00,0.00,0,1.40,64,81,1539,513,0.06
0,Aarón Martín,24,Bundesliga,Defender,Mainz 05,261,94,167,Spain,5,...,0.00,0.00,0.00,0,0.69,131,52,0,0,0.00
3,Abdallah Basit,21,Serie A,Midfielder,Benevento,0,0,0,Italy,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
2,Abdallahi Mohamed Mahmoud,21,La Liga,Defender,Deportivo Alavés,66,0,66,Mauritania,2,...,0.00,0.00,0.00,0,1.36,66,33,0,0,0.00
3,Abdelkabir Abqar,22,La Liga,Defender,Deportivo Alavés,0,0,0,Morocco,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
2,Abdou Diallo,25,Ligue 1,Defender,PSG,1488,716,772,France,22,...,0.00,0.00,0.00,0,0.60,149,68,298,1488,0.30

In [141]:
tot_df = tot_df.reset_index(drop=True)

tot_df[ : 15]

,players,age,league,position,Current Club,minutes_played_overall,minutes_played_home,minutes_played_away,nationality,appearances_overall,...,goals_per_90_overall,goals_per_90_home,goals_per_90_away,min_per_goal_overall,conceded_per_90_overall,min_per_conceded_overall,min_per_match,min_per_card_overall,min_per_assist_overall,cards_per_90_overall
0,Aaron Anthony Connolly,21,Premier League,Forward,Brighton & Hove Albion,790,397,393,Republic of Ireland,17,...,0.23,0.23,0.23,395,1.94,46,46,0,790,0.00
1,Aaron Cresswell,31,Premier League,Defender,West Ham United,3172,1552,1620,England,36,...,0.00,0.00,0.00,0,1.13,79,88,1057,397,0.09
2,Aaron Hickey,0,Serie A,Midfielder,Bologna,763,364,399,Scotland,11,...,0.00,0.00,0.00,0,1.77,51,69,153,0,0.59
3,Aaron Kamardin,19,Ligue 1,Defender,Olympique Marseille,0,0,0,France,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
4,Aaron Leya Iseka,23,Ligue 1,Forward,Metz,1010,609,401,Belgium,21,...,0.36,0.15,0.67,253,1.34,67,48,253,0,0.36
5,Aaron Ramsdale,23,Premier League,Goalkeeper,Sheffield United,3420,1710,1710,England,38,...,0.00,0.00,0.00,0,1.61,56,90,3420,0,0.03
6,Aaron Ramsey,30,Serie A,Midfielder,Juventus,1093,572,521,Wales,22,...,0.16,0.16,0.17,547,0.91,99,50,547,273,0.16
7,Aaron Wan-Bissaka,23,Premier League,Midfielder,Manchester United,3060,1530,1530,England,34,...,0.06,0.06,0.06,1530,0.97,93,90,1020,765,0.09
8,Aarón Escandell Banacloche,25,La Liga,Goalkeeper,Granada CF,450,180,270,Spain,5,...,0.00,0.00,0.00,0,1.60,56,90,450,0,0.20
9,Aarón Martín,24,La Liga,Defender,Celta de Vigo,1539,668,871,Spain,19,...,0.00,0.00,0.00,0,1.40,64,81,1539,513,0.06
10,Aarón Martín,24,Bundesliga,Defender,Mainz 05,261,94,167,Spain,5,...,0.00,0.00,0.00,0,0.69,131,52,0,0,0.00
11,Abdallah Basit,21,Serie A,Midfielder,Benevento,0,0,0,Italy,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
12,Abdallahi Mohamed Mahmoud,21,La Liga,Defender,Deportivo Alavés,66,0,66,Mauritania,2,...,0.00,0.00,0.00,0,1.36,66,33,0,0,0.00
13,Abdelkabir Abqar,22,La Liga,Defender,Deportivo Alavés,0,0,0,Morocco,0,...,0.00,0.00,0.00,0,0.00,0,0,0,0,0.00
14,Abdou Diallo,25,Ligue 1,Defender,PSG,1488,716,772,France,22,...,0.00,0.00,0.00,0,0.60,149,68,298,1488,0.30

In [142]:
tot_df.isna().sum()

players                          0
age                              0
league                           0
position                         0
Current Club                     0
minutes_played_overall           0
minutes_played_home              0
minutes_played_away              0
nationality                      0
appearances_overall              0
appearances_home                 0
appearances_away                 0
goals_overall                    0
goals_home                       0
goals_away                       0
assists_overall                  0
assists_home                     0
assists_away                     0
penalty_goals                    0
penalty_misses                   0
clean_sheets_overall             0
clean_sheets_home                0
clean_sheets_away                0
conceded_overall                 0
conceded_home                    0
conceded_away                    0
yellow_cards_overall             0
red_cards_overall                0
goals_involved_per_90_overall    0
assists_per_90_overall           0
goals_per_90_overall             0
goals_per_90_home                0
goals_per_90_away                0
min_per_goal_overall             0
conceded_per_90_overall          0
min_per_conceded_overall         0
min_per_match                    0
min_per_card_overall             0
min_per_assist_overall           0
cards_per_90_overall             0
dtype: int64

In [81]:
tot_df.drop(columns='Drb.1', inplace=True)

In [143]:
tot_df.to_csv('D:/Gray_Bigdata/src/00_Projects/data/total_player_2021_apps.csv')