In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.Container {width:85% !important;}
div.CodeMirror {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.output_area pre {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.output_wrapper pre {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
div.input {font-family:나눔고딕; font-size:13pt; line-height : 150%;}
</style>
"""))

# 각 포지션 별 세부 데이터 웹 크롤링

## 후스코어드에서 수비지표 가져오기

In [1]:
# ▶ 1. 필요한 패키지 로드
from selenium import webdriver # 동적 웹 크롤링
import time # 대기시간
import pandas as pd # 데이터 프레임화 해야하기 때문
import numpy as np
from pandas.io.html import read_html

In [70]:
# ▶ 2. 해당 리그 모든 선수의 수비 지표 크롤링
def defensive(url, sleep_time):  # url 주소와 대기시간을 매개변수로 받는다.
    chrome_driver = 'D:/Gray_Bigdata/src/07_Python/chromedriver.exe'
    driver = webdriver.Chrome(chrome_driver)
    driver.get(url)

    time.sleep(sleep_time)
    defense = driver.find_element_by_link_text('Defensive')
    defense.click()

    time.sleep(sleep_time)
    all_player = driver.find_element_by_link_text('All players')
    all_player.click()

    time.sleep(sleep_time)
    page = driver.find_element_by_link_text('last')
    total_page = int(page.get_attribute('data-page'))

    df_defensive = pd.DataFrame(columns=['Player', 'Apps', 'Mins', 'Tackles', 'Inter', 'Fouls',
                                         'Offsides', 'Clear', 'Drb', 'Blocks', 'OwnG', 'Rating'])

    for i in np.arange(total_page):
        time.sleep(sleep_time)
        table = driver.find_element_by_xpath(
            '//*[@id="statistics-table-defensive"]')
        # 전체 태그 중 id속성의 "" 사이의 속성을 가진 모든태그 선택
        table_html = table.get_attribute('innerHTML')

        df2 = read_html(table_html)[0]  # 0번 인덱스에 모든 값이 들어가있음
        df_defensive = pd.concat([df_defensive, df2], axis=0)

        driver.find_element_by_link_text('next').click()  # 크롤링 후 다음페이지로 이동

    return(df_defensive)

url = 'https://1xbet.whoscored.com/Regions/81/Tournaments/3/Seasons/7872/Stages/17682/PlayerStatistics/Germany-Bundesliga-2019-2020'
df = defensive(url, 2)

In [71]:
df.head()

,Player,Apps,Mins,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating,Player.1
0,"1Robert LewandowskiBayern, 33, FW",31,2762,0.6,0.2,1.0,-,0.4,0.4,-,-,8.13,"Robert Lewandowski Bayern, 33, FW"
1,"2Jadon SanchoBorussia Dortmund, 21, AM(CLR)",25(7),2292,0.4,0.4,0.3,-,0.1,0.5,-,-,7.64,"Jadon Sancho Borussia Dortmund, 21, AM(CLR)"
2,"3Timo WernerRBL, 25, AM(CLR),FW",33(1),2809,0.6,0.1,0.5,-,-,0.4,-,-,7.60,"Timo Werner RBL, 25, AM(CLR),FW"
3,"4Matheus CunhaHertha Berlin, 22, AM(CL),FW",9(2),747,0.9,0.9,2.3,-,0.1,0.6,0.1,-,7.56,"Matheus Cunha Hertha Berlin, 22, AM(CL),FW"
4,"5Alphonso DaviesBayern, 20, D(L),M(LR)",24(5),2234,2.4,1.1,0.9,0.6,1.2,0.7,0.2,-,7.52,"Alphonso Davies Bayern, 20, D(L),M(LR)"

In [72]:
# ▶ 3. 데이터 수집을 위한 데이터 전처리
# 쓸모없는 열 삭제
df = df.reset_index()
df.drop(['index', 'Player.1', 'Apps', 'Mins'], axis=1, inplace=True)

df.head()

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,"1Robert LewandowskiBayern, 33, FW",0.6,0.2,1.0,-,0.4,0.4,-,-,8.13
1,"2Jadon SanchoBorussia Dortmund, 21, AM(CLR)",0.4,0.4,0.3,-,0.1,0.5,-,-,7.64
2,"3Timo WernerRBL, 25, AM(CLR),FW",0.6,0.1,0.5,-,-,0.4,-,-,7.60
3,"4Matheus CunhaHertha Berlin, 22, AM(CL),FW",0.9,0.9,2.3,-,0.1,0.6,0.1,-,7.56
4,"5Alphonso DaviesBayern, 20, D(L),M(LR)",2.4,1.1,0.9,0.6,1.2,0.7,0.2,-,7.52

In [73]:
df.isna().sum()

Player      0
Tackles     0
Inter       0
Fouls       0
Offsides    0
Clear       0
Drb         0
Blocks      0
OwnG        0
Rating      0
dtype: int64

In [74]:
# Player에 이름만 넣기
spl = df['Player'].str.split(',')

print(spl)

0                  [1Robert LewandowskiBayern,  33,  FW]
1        [2Jadon SanchoBorussia Dortmund,  21,  AM(CLR)]
2                   [3Timo WernerRBL,  25,  AM(CLR), FW]
3        [4Matheus CunhaHertha Berlin,  22,  AM(CL), FW]
4            [5Alphonso DaviesBayern,  20,  D(L), M(LR)]
                             ...
493                         [494Yvon MvogoRBL,  27,  GK]
494     [495Martin HarnikWerder Bremen,  34,  M(LR), FW]
495      [496Daishawn RedanHertha Berlin,  20,  Forward]
496    [497Moritz NicolasUnion Berlin,  23,  Goalkeeper]
497         [498Jan-Luca RumpfPaderborn,  22,  Defender]
Name: Player, Length: 498, dtype: object

In [75]:
pls_list = []
for i in range(len(spl)):
    result_a = spl[i][0]
    pls_list.append(result_a)

df['Player'] = pls_list

df.head()

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,1Robert LewandowskiBayern,0.6,0.2,1.0,-,0.4,0.4,-,-,8.13
1,2Jadon SanchoBorussia Dortmund,0.4,0.4,0.3,-,0.1,0.5,-,-,7.64
2,3Timo WernerRBL,0.6,0.1,0.5,-,-,0.4,-,-,7.60
3,4Matheus CunhaHertha Berlin,0.9,0.9,2.3,-,0.1,0.6,0.1,-,7.56
4,5Alphonso DaviesBayern,2.4,1.1,0.9,0.6,1.2,0.7,0.2,-,7.52

In [76]:
df.loc[50:70]

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
50,51Dedryck BoyataHertha Berlin,0.9,2.2,0.8,0.5,5.6,0.3,1.1,-,7.04
51,52Julian BrandtBorussia Dortmund,1.5,0.5,0.4,-,0.3,0.9,0.1,-,7.04
52,53Florian NiederlechnerAugsburg,0.6,0.2,1.4,-,1.2,0.5,0.2,1,7.03
53,54Jordan TorunarighaHertha Berlin,1.8,1.7,0.9,0.7,4.1,0.5,1.0,-,7.03
54,55WilliamWolfsburg,3.4,1.5,1.9,0.1,1.6,2.0,0.2,-,7.03
55,56Salif SanéSchalke,1.1,1.4,0.7,0.5,3.3,0.5,0.5,-,7.02
56,57Sebastian SchonlauPaderborn,2.8,1.7,0.9,1.1,5.7,1.1,0.7,-,7.01
57,58Dani OlmoRBL,1.7,0.3,0.8,0.1,0.5,1.0,0.1,-,7.01
58,59Maximilian ArnoldWolfsburg,1.3,0.8,1.6,0.1,1.0,1.4,0.2,-,7.01
59,60David AlabaBayern,1.1,1.0,0.4,0.6,1.2,0.3,0.4,-,6.99
60,61Milot RashicaWerder Bremen,0.8,0.2,1.0,-,0.4,0.9,0.1,-,6.99
61,62Toni LeistnerFC Koln,1.5,2.5,1.2,0.3,4.3,0.6,0.5,-,6.99
62,63Omar MascarellSchalke,1.8,2.7,1.1,-,1.7,1.6,0.6,-,6.99
63,64Florian NeuhausBorussia M.Gladbach,1.4,0.9,0.7,-,0.2,1.4,0.1,-,6.98
64,65Axel WitselBorussia Dortmund,1.0,1.1,1.4,-,0.6,0.7,0.3,-,6.98
65,66Dan-Axel ZagadouBorussia Dortmund,1.1,1.0,0.4,0.8,2.3,0.1,0.5,-,6.98
66,67Sven BenderLeverkusen,1.6,2.0,0.8,0.5,2.6,0.8,0.4,-,6.98
67,68Thomas DelaneyBorussia Dortmund,2.0,2.4,1.8,0.1,2.2,0.5,0.6,1,6.98
68,69Lars BenderLeverkusen,2.3,1.3,1.0,0.4,1.5,1.1,0.3,-,6.97
69,70Maximilian MittelstädtHertha Berlin,2.3,2.0,0.9,0.2,1.9,1.1,0.2,-,6.97
70,71Willi OrbanRBL,1.7,1.3,0.5,0.8,4.3,0.7,0.3,-,6.97

In [2]:
engla_teams = ['Man City', 'Liverpool', 'Chelsea', 'Man Utd', 'Arsenal', 'Tottenham', 'Huddersfield', 'Watford',
               'Bournemouth', 'Crystal Palace', 'Leicester', 'Wolves', 'Everton', 'Cardiff', 'Southampton', 'West Ham',
               'Fulham', 'Newcastle', 'Brighton', 'Burnley', 'Leeds', 'Norwich', 'Aston Villa', 'Sheff Utd', 'West Brom']

italy_teams = ['Juventus', 'Atalanta', 'AC Milan', 'Udinese', 'Roma', 'Napoli', 'Lazio', 'SPAL', 'Parma Calcio',
               'Sampdoria', 'Torino', 'Fiorentina', 'Sassuolo', 'Inter', 'Genoa', 'Cagliari', 'Bologna', 'Chievo', 'Empoli',
               'Frosinone', 'Brescia', 'Lecce', 'Verona', 'Crotone', 'Benevento', 'Spezia']

franc_teams = []

germa_teams = ['Mainz', 'Leverkusen', 'Hoffenheim', 'Fortuna Duesseldorf', 'Eintracht Frankfurt', 'Freiburg',\
               'Werder Bremen', 'Augsburg', 'Borussia Dortmund', 'Bayern', 'Borussia M.Gladbach', 'Hannover', 'RBL',\
               'Nuernberg', 'Wolfsburg', 'Schalke', 'Stuttgart', 'Hertha Berlin', 'FC Koln', 'Union Berlin', 'Mainz',\
               'Paderborn']

spain_teams = ['Barcelona', 'Real Sociedad', 'Celta Vigo', 'Valencia', 'Real Madrid', 'Atletico', 'Athletic Bilbao', 'Espanyol',\
               'Levante', 'Eibar', 'Getafe', 'Real Betis', 'Leganes', 'Deportivo Alaves', 'Real Valladolid', 'SD Huesca', 'Sevilla',\
               'Villarreal', 'Girona', 'Rayo Vallecano', 'Osasuna', 'Mallorca', 'Granada', 'Cadiz', 'Elche']

In [3]:
def eng_players(name):
    for team in engla_teams:
        name = name.replace(team, "")
    return name

In [4]:
def ger_players(name):
    for team in germa_teams:
        name = name.replace(team, "")
    return name

In [5]:
def italy_players(name):
    for team in italy_teams:
        name = name.replace(team, "")
    return name

In [6]:
def spain_players(name):
    for team in spain_teams:
        name = name.replace(team, "")
    return name

In [78]:
pls_list = []
for player in df['Player']:
    result_b = ger_players(player)
    pls_list.append(result_b)

df['Player'] = pls_list
df.head()

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,1Robert Lewandowski,0.6,0.2,1.0,-,0.4,0.4,-,-,8.13
1,2Jadon Sancho,0.4,0.4,0.3,-,0.1,0.5,-,-,7.64
2,3Timo Werner,0.6,0.1,0.5,-,-,0.4,-,-,7.60
3,4Matheus Cunha,0.9,0.9,2.3,-,0.1,0.6,0.1,-,7.56
4,5Alphonso Davies,2.4,1.1,0.9,0.6,1.2,0.7,0.2,-,7.52

In [79]:
#  선수 이름 앞 숫자 자르기, 뒤 팀명 자르기
df['Player'] = df['Player'].replace(r'[0-9]', "", regex=True)

df.head()

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,Robert Lewandowski,0.6,0.2,1.0,-,0.4,0.4,-,-,8.13
1,Jadon Sancho,0.4,0.4,0.3,-,0.1,0.5,-,-,7.64
2,Timo Werner,0.6,0.1,0.5,-,-,0.4,-,-,7.60
3,Matheus Cunha,0.9,0.9,2.3,-,0.1,0.6,0.1,-,7.56
4,Alphonso Davies,2.4,1.1,0.9,0.6,1.2,0.7,0.2,-,7.52

In [80]:
# '-'로 처리된 부분 NaN으로 처리하기
df = df.replace("-", "0.0")

df.head()

,Player,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG,Rating
0,Robert Lewandowski,0.6,0.2,1.0,0.0,0.4,0.4,0.0,0.0,8.13
1,Jadon Sancho,0.4,0.4,0.3,0.0,0.1,0.5,0.0,0.0,7.64
2,Timo Werner,0.6,0.1,0.5,0.0,0.0,0.4,0.0,0.0,7.60
3,Matheus Cunha,0.9,0.9,2.3,0.0,0.1,0.6,0.1,0.0,7.56
4,Alphonso Davies,2.4,1.1,0.9,0.6,1.2,0.7,0.2,0.0,7.52

In [81]:
# csv파일로 저장하기
df.to_csv('D:/Gray_Bigdata\src/00_Projects/data/ger_1920_defensive_stats.csv')

## 후스코어드에서 미드필드 지표 가져오기

In [57]:
def passing(url, sleep_time):  # url 주소와 대기시간을 매개변수로 받는다.
    chrome_driver = 'D:/Gray_Bigdata/src/07_Python/chromedriver.exe'
    driver = webdriver.Chrome(chrome_driver)
    driver.get(url)

    time.sleep(sleep_time)
    passing = driver.find_element_by_link_text('Passing')
    passing.click()

    time.sleep(sleep_time)
    all_player = driver.find_element_by_link_text('All players')
    all_player.click()

    time.sleep(sleep_time)
    page = driver.find_element_by_link_text('last')
    total_page = int(page.get_attribute('data-page'))

    df_passing = pd.DataFrame(columns=['Player', 'Apps', 'Mins', 'Assists', 'KeyP', 'AvgP',
                                         'PS%', 'Crosses', 'LongB', 'ThrB', 'Rating'])

    for i in np.arange(total_page):
        time.sleep(sleep_time)
        table = driver.find_element_by_xpath(
            '//*[@id="statistics-table-passing"]')
        # 전체 태그 중 id속성의 "" 사이의 속성을 가진 모든태그 선택
        table_html = table.get_attribute('innerHTML')

        df2 = read_html(table_html)[0]  # 0번 인덱스에 모든 값이 들어가있음
        df_passing = pd.concat([df_passing, df2], axis=0)

        driver.find_element_by_link_text('next').click()  # 크롤링 후 다음페이지로 이동

    return(df_passing)


url = 'https://1xbet.whoscored.com/Regions/206/Tournaments/4/Seasons/7466/Stages/16546/PlayerStatistics/Spain-LaLiga-2018-2019'
df = passing(url, 2)

In [58]:
df.head()

,Player,Apps,Mins,Assists,KeyP,AvgP,PS%,Crosses,LongB,ThrB,Rating,Player.1
0,"1Lionel MessiBarcelona, 34, AM(CR),FW",29(5),2710,13,2.7,53.8,81.3,0.4,3.4,0.9,8.48,"Lionel Messi Barcelona, 34, AM(CR),FW"
1,"2Álex SolaReal Sociedad, 22, Defender",1,90,-,1.0,52.0,80.8,1,1,-,8.03,"Álex Sola Real Sociedad, 22, Defender"
2,"3Luis SuárezBarcelona, 34, AM(CLR),FW",31(2),2830,6,1.4,29.0,75.3,0.2,1.5,0.1,7.57,"Luis Suárez Barcelona, 34, AM(CLR),FW"
3,"4Iago AspasCelta Vigo, 34, AM(CR),FW",26(1),2262,6,2.1,32.1,82.0,0.2,1.4,0.2,7.51,"Iago Aspas Celta Vigo, 34, AM(CR),FW"
4,"5Daniel ParejoValencia, 32, M(C)",35(1),3063,7,2.3,61.5,85.8,1.9,5.6,0.1,7.40,"Daniel Parejo Valencia, 32, M(C)"

In [59]:
# ▶ 3. 데이터 수집을 위한 데이터 전처리
# 쓸모없는 열 삭제
df = df.reset_index()
df.drop(['index', 'Player.1', 'Apps', 'Mins'], axis=1, inplace=True)

df.head()

,Player,Assists,KeyP,AvgP,PS%,Crosses,LongB,ThrB,Rating
0,"1Lionel MessiBarcelona, 34, AM(CR),FW",13,2.7,53.8,81.3,0.4,3.4,0.9,8.48
1,"2Álex SolaReal Sociedad, 22, Defender",-,1.0,52.0,80.8,1,1,-,8.03
2,"3Luis SuárezBarcelona, 34, AM(CLR),FW",6,1.4,29.0,75.3,0.2,1.5,0.1,7.57
3,"4Iago AspasCelta Vigo, 34, AM(CR),FW",6,2.1,32.1,82.0,0.2,1.4,0.2,7.51
4,"5Daniel ParejoValencia, 32, M(C)",7,2.3,61.5,85.8,1.9,5.6,0.1,7.40

In [60]:
df.isna().sum()

Player     0
Assists    0
KeyP       0
AvgP       0
PS%        0
Crosses    0
LongB      0
ThrB       0
Rating     0
dtype: int64

In [61]:
# Player에 이름만 넣기
spl = df['Player'].str.split(',')

print(spl)

0             [1Lionel MessiBarcelona,  34,  AM(CR), FW]
1              [2Álex SolaReal Sociedad,  22,  Defender]
2             [3Luis SuárezBarcelona,  34,  AM(CLR), FW]
3              [4Iago AspasCelta Vigo,  34,  AM(CR), FW]
4                   [5Daniel ParejoValencia,  32,  M(C)]
                             ...
539           [540Ivi LópezReal Valladolid,  27,  AM(L)]
540       [541Alexander SzymanowskiLeganes,  32,  AM(L)]
541    [542Franco Di SantoRayo Vallecano,  32,  AM(CL...
542                  [543Axel WernerSD Huesca,  25,  GK]
543         [544Yoel RodríguezReal Valladolid,  32,  GK]
Name: Player, Length: 544, dtype: object

In [62]:
pls_list = []
for i in range(len(spl)):
    result_a = spl[i][0]
    pls_list.append(result_a)

df['Player'] = pls_list
df.head()

                    Player Assists KeyP  AvgP   PS% Crosses LongB ThrB  Rating
0   1Lionel MessiBarcelona      13  2.7  53.8  81.3     0.4   3.4  0.9    8.48
1  2Álex SolaReal Sociedad       -  1.0  52.0  80.8       1     1    -    8.03
2    3Luis SuárezBarcelona       6  1.4  29.0  75.3     0.2   1.5  0.1    7.57
3    4Iago AspasCelta Vigo       6  2.1  32.1  82.0     0.2   1.4  0.2    7.51
4   5Daniel ParejoValencia       7  2.3  61.5  85.8     1.9   5.6  0.1    7.40

In [63]:
#  선수 이름 앞 숫자 자르기, 뒤 팀명 자르기
df['Player'] = df['Player'].replace(r'[0-9]', "", regex=True)

df.head()

                   Player Assists KeyP  AvgP   PS% Crosses LongB ThrB  Rating
0   Lionel MessiBarcelona      13  2.7  53.8  81.3     0.4   3.4  0.9    8.48
1  Álex SolaReal Sociedad       -  1.0  52.0  80.8       1     1    -    8.03
2    Luis SuárezBarcelona       6  1.4  29.0  75.3     0.2   1.5  0.1    7.57
3    Iago AspasCelta Vigo       6  2.1  32.1  82.0     0.2   1.4  0.2    7.51
4   Daniel ParejoValencia       7  2.3  61.5  85.8     1.9   5.6  0.1    7.40

In [65]:
ls_list = []
for player in df['Player']:
    result_b = spain_players(player)
    ls_list.append(result_b)

df['Player'] = ls_list
df.head()

          Player Assists KeyP  AvgP   PS% Crosses LongB ThrB  Rating
0   Lionel Messi      13  2.7  53.8  81.3     0.4   3.4  0.9    8.48
1      Álex Sola       -  1.0  52.0  80.8       1     1    -    8.03
2    Luis Suárez       6  1.4  29.0  75.3     0.2   1.5  0.1    7.57
3     Iago Aspas       6  2.1  32.1  82.0     0.2   1.4  0.2    7.51
4  Daniel Parejo       7  2.3  61.5  85.8     1.9   5.6  0.1    7.40

In [66]:
df = df.replace("-", "0.0")

df.head()

          Player Assists KeyP  AvgP   PS% Crosses LongB ThrB  Rating
0   Lionel Messi      13  2.7  53.8  81.3     0.4   3.4  0.9    8.48
1      Álex Sola     0.0  1.0  52.0  80.8       1     1  0.0    8.03
2    Luis Suárez       6  1.4  29.0  75.3     0.2   1.5  0.1    7.57
3     Iago Aspas       6  2.1  32.1  82.0     0.2   1.4  0.2    7.51
4  Daniel Parejo       7  2.3  61.5  85.8     1.9   5.6  0.1    7.40

In [67]:
# csv파일로 저장하기
df.to_csv('D:/Gray_Bigdata/src/00_Projects/data/spa_1819_passing_stats.csv')

## 후스코어드에서 공격지표 가져오기

In [46]:
def offensive(url, sleep_time):  # url 주소와 대기시간을 매개변수로 받는다.
    chrome_driver = 'D:/Gray_Bigdata/src/07_Python/chromedriver.exe'
    driver = webdriver.Chrome(chrome_driver)
    driver.get(url)

    time.sleep(sleep_time)
    offensive = driver.find_element_by_link_text('Offensive')
    offensive.click()

    time.sleep(sleep_time)
    all_player = driver.find_element_by_link_text('All players')
    all_player.click()

    time.sleep(sleep_time)
    page = driver.find_element_by_link_text('last')
    total_page = int(page.get_attribute('data-page'))

    df_offensive = pd.DataFrame(columns=['Player', 'Apps', 'Mins', 'Goals', 'Assists', 'SpG',
                                         'KeyP', 'Drb', 'Fouled', 'Off', 'Disp', 'UnsTch', 'Rating'])

    for i in np.arange(total_page):
        time.sleep(sleep_time)
        table = driver.find_element_by_xpath(
            '//*[@id="statistics-table-offensive"]')
        # 전체 태그 중 id속성의 "" 사이의 속성을 가진 모든태그 선택
        table_html = table.get_attribute('innerHTML')

        df2 = read_html(table_html)[0]  # 0번 인덱스에 모든 값이 들어가있음
        df_offensive = pd.concat([df_offensive, df2], axis=0)

        driver.find_element_by_link_text('next').click()  # 크롤링 후 다음페이지로 이동

    return(df_offensive)

url = 'https://1xbet.whoscored.com/Regions/108/Tournaments/5/Seasons/7468/Stages/16548/PlayerStatistics/Italy-Serie-A-2018-2019'
df = offensive(url, 2)

In [47]:
df.head()

,Player,Apps,Mins,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating,Player.1
0,"1Cristiano RonaldoJuventus, 36, M(L),FW",30(1),2689,21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68,"Cristiano Ronaldo Juventus, 36, M(L),FW"
1,"2Papu GómezAtalanta, 33, M(CL),FW",34(1),2913,7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64,"Papu Gómez Atalanta, 33, M(CL),FW"
2,"3Josip IlicicAtalanta, 33, AM(CLR),FW",23(8),2151,12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39,"Josip Ilicic Atalanta, 33, AM(CLR),FW"
3,"4SusoAC Milan, 27, AM(CLR),FW",35,3031,7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39,"Suso AC Milan, 27, AM(CLR),FW"
4,"5Rodrigo de PaulUdinese, 27, AM(CLR),FW",36,3194,9,8,2.4,2.7,2.3,2.6,-,1.8,2.4,7.37,"Rodrigo de Paul Udinese, 27, AM(CLR),FW"

In [48]:
# ▶ 3. 데이터 수집을 위한 데이터 전처리
# 쓸모없는 열 삭제
df = df.reset_index()
df.drop(['index', 'Player.1', 'Apps', 'Mins'], axis=1, inplace=True)

df.head()

,Player,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,"1Cristiano RonaldoJuventus, 36, M(L),FW",21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68
1,"2Papu GómezAtalanta, 33, M(CL),FW",7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64
2,"3Josip IlicicAtalanta, 33, AM(CLR),FW",12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39
3,"4SusoAC Milan, 27, AM(CLR),FW",7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39
4,"5Rodrigo de PaulUdinese, 27, AM(CLR),FW",9,8,2.4,2.7,2.3,2.6,-,1.8,2.4,7.37

In [49]:
df.isna().sum()

Player     0
Goals      0
Assists    0
SpG        0
KeyP       0
Drb        0
Fouled     0
Off        0
Disp       0
UnsTch     0
Rating     0
dtype: int64

In [50]:
# Player에 이름만 넣기
spl = df['Player'].str.split(',')

print(spl)

0           [1Cristiano RonaldoJuventus,  36,  M(L), FW]
1                 [2Papu GómezAtalanta,  33,  M(CL), FW]
2             [3Josip IlicicAtalanta,  33,  AM(CLR), FW]
3                     [4SusoAC Milan,  27,  AM(CLR), FW]
4           [5Rodrigo de PaulUdinese,  27,  AM(CLR), FW]
                             ...
565    [566Nicky Medja BelokoFiorentina,  21,  Midfie...
566       [567Stephy MavididiJuventus,  23,  AM(LR), FW]
567          [568Guido GuerrieriLazio,  25,  Goalkeeper]
568       [569Carlo PinsoglioJuventus,  31,  Goalkeeper]
569     [570Strahinja TanasijevicChievo,  24,  Defender]
Name: Player, Length: 570, dtype: object

In [51]:
pls_list = []
for i in range(len(spl)):
    result_a = spl[i][0]
    pls_list.append(result_a)

df['Player'] = pls_list
df.head()

,Player,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,1Cristiano RonaldoJuventus,21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68
1,2Papu GómezAtalanta,7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64
2,3Josip IlicicAtalanta,12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39
3,4SusoAC Milan,7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39
4,5Rodrigo de PaulUdinese,9,8,2.4,2.7,2.3,2.6,-,1.8,2.4,7.37

In [52]:
#  선수 이름 앞 숫자 자르기, 뒤 팀명 자르기
df['Player'] = df['Player'].replace(r'[0-9]', "", regex=True)

df.head()

,Player,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,Cristiano RonaldoJuventus,21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68
1,Papu GómezAtalanta,7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64
2,Josip IlicicAtalanta,12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39
3,SusoAC Milan,7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39
4,Rodrigo de PaulUdinese,9,8,2.4,2.7,2.3,2.6,-,1.8,2.4,7.37

In [54]:
ls_list = []
for player in df['Player']:
    result_b = italy_players(player)
    ls_list.append(result_b)

df['Player'] = ls_list
df.head()

,Player,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,Cristiano Ronaldo,21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68
1,Papu Gómez,7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64
2,Josip Ilicic,12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39
3,Suso,7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39
4,Rodrigo de Paul,9,8,2.4,2.7,2.3,2.6,-,1.8,2.4,7.37

In [55]:
df = df.replace("-", "0.0")

df.head()

,Player,Goals,Assists,SpG,KeyP,Drb,Fouled,Off,Disp,UnsTch,Rating
0,Cristiano Ronaldo,21,8,5.7,1.5,1.5,1.6,0.9,1.3,1.7,7.68
1,Papu Gómez,7,11,3,3.2,2.2,2.7,0.1,2.2,1.9,7.64
2,Josip Ilicic,12,7,3.3,2.1,2.5,2.5,0.2,2.5,2.4,7.39
3,Suso,7,10,2.7,2.8,1.9,2.3,0.2,1.8,1.8,7.39
4,Rodrigo de Paul,9,8,2.4,2.7,2.3,2.6,0.0,1.8,2.4,7.37

In [56]:
# csv파일로 저장하기
df.to_csv('D:/Gray_Bigdata/src/00_Projects/data/ita_1819_offensive_stats.csv')